### ISSUE TITLE
Code principles - road to a CONTRIBUTING.md

### ISSUE THREAD

**Issue by epijim** [openpharma/visR#2]
What are the core things that need to be decided in order to move towards to a simple but expandable way to structure the package?

**Comment by kalimu** [comment]
James asked us if we could come up with some suggestions that can be helpful in the further development of the visR package. I've seen the repo and I've gathered some thoughts to share with you. Please treat them as points for consideration or discussion - I'm not sure what is the optimal approach here and what would be the most helpful solutions for you in the future. I've tried to come up with some recommendations anyway.

1) consistent API
My main concern is that when there would be many contributors to the package it would be difficult to maintain consistency in the package API of the exported functions. And that will cause more and more difficulties for end-users. To prevent this you should agree on predefined rules for naming conventions, functions & argument names, functions structure. I will try to tackle some examples below...

2) naming conventions
I would recommend using snake_case naming convention for both functions and arguments. You already are doing it, but not always consistent. There are some arguments like (N_unit) that start with a capital letter which would be good to avoid. 

3) function prefixes vs. package name
Function prefixes based on package name could be very helpful when one works with autocompletion, but they usually reflect the package name (e.g. str_ for stringr::)
In visR package we have functions starting from pvr_ which could be confusing ("p" stands for pharma perhaps?)

4) generic vs. domain language
As the goal of the package is to promote some standards in pharma industry, I guess that using domain language in function names is natural and will help find proper functions for common problems. For example plot_surival() should be better than plot_lines() and plot_attrition() should be better than plot_diagram().
Using generic language is risky as there may be some cases for which the function is not optimal, and those cases could be distinguished with domain language. So instead of plot_stacked_barchart() we may want to use plot_proportions() or plot_proportion_groups() or plot_proportions_subgroups() or plot_patients_subgroups() or plot_subgroups().
We can have both (domain- and generic-language) functions in the package, but I would recommend exporting mostly domain-language functions, keeping generic as internal ones, and adding new domain functions as wrappers for generics if necessary.

5) structure of the function names
It would be useful to have a consistent template for a function name like:
prefix_verb_noun_[~adjective/special case]
for example:
visr_plot_survival()
visr_plot_subgroups_stacked()
visr_create_table_cross()
visr_create_table_one()
visr_render_table_html()
visr_render_table_markdown()

6) consistency of arguments
If one function takes the main input data with argument 'data' other functions should do it too.
The same arguments should mean the same thing across all the functions (if possible). So it would be good to standardize arguments not only per function but also per package.

7) pipe friendly
That would help in the future when we would have more complex pipelines, like:
visr_create_table_cross() %>% visr_render_table_html()
or 
visr_create_attrition_arrays() %>% visr_plot_attrition()

That's what I have right now. Not sure if those all examples above make sense, but I hope they would be a little helpful for you anyway.

Best,
Kamil

**Comment by epijim** [comment]
Relevant wiki content: https://github.com/openpharma/visR/wiki/Package-Architecture

**Comment by cschaerfe** [comment]
We have a page on the wiki on contributing: https://github.com/openpharma/visR/wiki/Contribute - do we need a CONTRIBUTING.md as well? Or maybe just that?

**Comment by epijim** [comment]
I’d recommend to have something in CONTRIBUTING.md, even if it’s just a link to the wiki, as Github expects it there. eg if you do a pull request and that file exists, it will remind people to read the doc when wanting to commit/PR.

**Comment by cschaerfe** [comment]
Thanks, that's good to know. We'll add one then.
