### ISSUE TITLE
Check if GT is still robust after the major releases they had

### ISSUE THREAD

**Issue by timtreis** [openpharma/visR#299]
Daniel (gtsummary) mentioned that GT had a big release and made major changes to their API. We're requiring [GT 0.1.0](https://github.com/openpharma/visR/blob/d7929a026f354e3ebaae47837764e9035f62adcf/DESCRIPTION#L43), which was supposedly pre-CRAN?  maybe me should check if our old code still runs without problems.

@cschaerfe

**Comment by SHAESEN2** [comment]
Can we also remove the dependency on glue? and only import the pipe from magrittr?

**Comment by ddsjoberg** [comment]
The gt package was at version 0.1.0 throughout its pre-CRAN development. I don't recall exactly when, but there was a major update to the internals and some of the functions one one point. I _think_ it was after the first CRAN release, but I am not 100% certain.

Since gt is in the Suggests section, the version will never be checked FYI. Perhaps at the top of the gt section of `render()` you could add `rlang::check_installed("gt", version = "0.3.1")` to add a version check. It's also difficult to check old versions of pkgs. If you suspect there have been breaking changes in a pkg, I would suggest increasing the min required version to avoid potential issues.
