### ISSUE TITLE
Documentation in S3 method `visr()`

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/visR#301]
Some arguments are documented for each class/method. When these arguments are documented multiple times, the last one is used in the help file.

For example, the `visr(x=)` argument is documented as 
- `@param x Object of class 'survfit'`
- `@param x Object of class 'attritiontable' with each row corresponding to an inclusion step in the cohort and minimally a description and a count column`

Only the last one is shown in the rendered help file.

**Comment by SHAESEN2** [comment]
Proposal to put all documentation at the top instead of per method. 
@param x. We can use markdown syntax for a bulleted list to specify for which class x represents what.

@param x a visR object
- objects of class `survift`
- object of class `something else`
@param x a visR object
- objects of class `survift`
- object of class `something else`
