### ISSUE TITLE
`pkgdown::build_site()` not working due to issue in `vr_alluvial_plot`

### ISSUE THREAD

**Issue by epijim** [openpharma/visR#51]
#### Issue description

`pkgdown::build_site()` not working due to issue in `vr_alluvial_plot`

#### Steps to reproduce the issue

Run `vignettes/Alluvial.Rmd` up to line 79 using R 4.0 and the latest version of tibble.

#### What's the actual result?

```r
vr_alluvial_plot(dataset,
                 id = "PatientID",
                 linename = "LineName",
                 linenumber = "LineNumber",
                 data_source = "Simulatation")

Error: Must extract column with a single valid subscript.
x Subscript `tibble_vars[[i]]` has value 0 but must be a positive location.
Run `rlang::last_error()` to see where the error occurred. 
```
#### Additional details / screenshot

May be an R 4.0 issue?

**Comment by kawap** [comment]
@epijim  I was writing about this issue in #49 .

citation of myself from this PR:

Working on that I have met some troubles. During CI build, after installation of all newest versions of dependencies, Alluvial vignette throw mysterious error while running vr_alluvial_plot() function:
`The subscript 'tibble_vars[[i]]' has value 0 but must be a positive location..`
I have been digging and It takes me a piece of time to find that it is as follows:
function `easyalluvial::alluvial_long()` is calling inside `dplyr::select_if()` on tibble handling data where columns in the tibble are named using 'i' (iterator). In the past there have been already problem like that: tidyverse/dplyr#4380 but this time I have found that it is not caused by updating of dplyr but latest tibble 3.0.0 released 16 days ago. When I force installation of previous version of tibble in DESCRIPTION FILE then everything works fine. So it is temporary solution until tibble package team will not fix that.

**Comment by epijim** [comment]
thanks @kawap - one thing that confuses me though is that the code in `visR` doesn't work, but it does work if you use the example in `easyalluvial::alluvial_long()`'s examples.

e.g. this works on the latest tibble:

```r
library(easyalluvial)
data = quarterly_flights
alluvial_long( data, key = qu, value = mean_arr_delay, id = tailnum, fill_by = 'last_variable' )
```

**Comment by kawap** [comment]
> ```r
> library(easyalluvial)
> data = quarterly_flights
> alluvial_long( data, key = qu, value = mean_arr_delay, id = tailnum, fill_by = 'last_variable' )
> ```

Our "key" is "linenumber" column with values : 0,1,2,3,4 
In quarterly_fligths example data, "key" is "qu" with values: "Q1", "Q2", "Q3", "Q4". 

 then in [alluvial_long.R](https://github.com/erblast/easyalluvial/blob/master/R/alluvial_long.R) in line 261:
`factor_cols = names( select_if(data_spread, is.factor) )`
 tibble cause problem because of data_spread columns names: `0`, `1`, `2`, `3`, `4` .

... and  seting "linenumber" as character or factor can't help. 

**Workaround:**
Only if we will overwrite all "linenumber" column values for exalple like "0" -> "line 0" or "L0" or something like that, for all lines numbers then problem will not appear, but it is not very good solution
